version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
      target: database
    ports:
      - "5444:5432"
    volumes:
      - notification_server_pgdata:/var/lib/postgresql/notification_data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: notification_db
      TZ: Asia/Tokyo
    restart: always

volumes:
  notification_server_pgdata: